### ISSUE TITLE
Entries shown on wrong day

### ISSUE THREAD

**Issue by ralfw** [UdaraJay/Pile#35] opened 2023-11-29 09:44 UTC
I wrote 3 entries on Nov 27th, and more on Nov 28th. But Pile shows the dots for the entries on the next days:

<img width="241" alt="image" src="https://github.com/UdaraJay/Pile/assets/132662/d8593427-87f5-4ab1-951c-26d60cea52c8">

**Comment by UdaraJay** [comment] 2023-11-30 00:08
I had noticed dots shifting by a day at times as well. It had to do with how the entry timestamps were parsed for comparison to place dots along the timeline. It's been fixed by doing the comparison based on the date component only, in the local time zone. It should work as intended in the next release.

**Closed** 2023-12-02 04:59 UTC
Labels: bug
